### ISSUE TITLE
SharePoint 2013 Project System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by kondotak** [ArxOne/MrAdvice#109]
Hey buddy, got another for you.  Just tried updating to newest code base 2.5.3.  Came across the error below.  Steps to reproduce are...

1) VS2015 Ent.
2) New Project
3) "SharePoint 2013 - Empty Project" template. target 4.5, Farm solution when asked
3) Add Nuget package for 2.5.3.
4) Compile

The non-SharePoint projects compile without issue.

Internal error: System.IO.FileNotFoundException: Could not load file or assembly 'MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8' or one of its dependencies. The system cannot find the file specified.
File name: 'MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at ArxOne.MrAdvice.MrAdviceStitcher.Process(AssemblyStitcherContext context)	SPTestProj

**Comment by picrap** [comment]
Well, this is a known problem, not only happening with Sharepoint projects, unfortunately. I'll take a look at it again.

**Comment by picrap** [comment]
Try 2.5.4 and let me know (this is a lazy and blind fix, so don't expect much from it :wink:)

**Comment by kondotak** [comment]
Not fixed :(  The last version that worked is 2.3.4

**Comment by kondotak** [comment]
I found a bit of a work-around, but it's not clean and not portable.  If i deploy MrAdvice.dll into the GAC using gacutil, I no longer see the error during compilation.  

Another difference between the normal class library test and the Sharepoint proj is that the SharePoint Proj DLL's are destined for the GAC, which means they must be signed.  I dunno if that matters, just thought I'd mention.

**Comment by picrap** [comment]
Any information can be useful. Thanks!

**Comment by picrap** [comment]
There are some changes in 2.5.8 (and more diagnostic in case of failure).
Let me know!

**Comment by kondotak** [comment]
Just tried 2.5.15, still nothing, this little bug is elusive huh.  MrAdvice.dll not in GAC

![image](https://user-images.githubusercontent.com/17506502/29255291-e4e5c250-806d-11e7-8934-dfce3f213bc0.png)

**Comment by picrap** [comment]
Could you test 2.5.19?
