### ISSUE TITLE
Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by 24code** [ArxOne/MrAdvice#129]
always occur the below error
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at ArxOne.MrAdvice.?Invocation.ProceedAspect(Object , Object[] , RuntimeMethodHandle , RuntimeMethodHandle , Type[] )
   at Beefun.Deliver.Operation.DeliverOrderPost.SaveBill[TBill](TBill bill, AbstractBillAction`1 action)
   at Beefun.Deliver.Operation.DeliverOrderPost.DoPostCoreOfGroup[T](DbHelper dbHelper, T saleBill, IList`1 vchcodes, GroupDeliverBill mergedbill) in e:\JenkinsBin\jobs\Beefun_GIT\workspace\srcs\Beefun.Deliver\Operation\DeliverOrderPost.cs:line 952
   at Beefun.Deliver.Operation.DeliverOrderPost.PostCore[T](DbHelper dbHelper, T saleBill, IList`1 vchcodes, GroupDeliverBill mergedbill) in e:\JenkinsBin\jobs\Beefun_GIT\workspace\srcs\Beefun.Deliver\Operation\DeliverOrderPost.cs:line 768

**Comment by picrap** [comment]
Do you expect me to guess you code and configuration? 😆 
So if you want me to help, I need a sample. I suggest you reduce MrAdvice use until it works again, then you can see where it fails.
