### ISSUE TITLE
Task.Run async ... await fails on .NetCore (.NetFramework works)

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#134]
May be can be helpful for someone.

Was difficult to find in a big project why the weaving stops without any extra information... This line caused the problem:

```C#
 Task.Run(async () => { await OpenSocketHandler(client); });
```

```TXT
1>MrAdvice 2.5.24 weaved module 'JCore, Version=1.437.2018.727, Culture=neutral, PublicKeyToken=null' (targeting framework ) in 1632ms
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error : Unhandled exception: dnlib.DotNet.Writer.ModuleWriterException: **Couldn't find an instruction, maybe it was removed. It's still being referenced by some code or by the PDB**
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.dnlib.DotNet.Writer.IWriterError.Error(String message)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.SerializerMethodContext.GetOffset(Instruction instr)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Pdb.Portable.PortablePdbCustomDebugInfoWriter.WriteAsyncMethodSteppingInformation(PdbAsyncMethodCustomDebugInfo cdi)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Pdb.Portable.PortablePdbCustomDebugInfoWriter.Write(PdbCustomDebugInfo cdi)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.AddCustomDebugInformationCore(SerializerMethodContext serializerMethodContext, UInt32 encodedToken, PdbCustomDebugInfo cdi, Guid cdiGuid)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.AddCustomDebugInformation(SerializerMethodContext serializerMethodContext, UInt32 token, UInt32 encodedToken, PdbCustomDebugInfo cdi)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.AddCustomDebugInformationCore(SerializerMethodContext serializerMethodContext, Table table, UInt32 rid, IList`1 cdis)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.AddCustomDebugInformationList(MethodDef method, UInt32 rid, UInt32 localVarSigToken)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.WriteMethodBodies()
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.Create()
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.MetaData.CreateTables()
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at StitcherBoy.Reflection.ModuleManager.Write(String assemblyOriginatorKeyFile)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at StitcherBoy.Weaving.Build.AssemblyStitcher.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAssemblyPath)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
1>C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error :    at StitcherTask`1.Run(Boolean fromExe)
```

**Comment by hhblaze** [comment]
Btw, all these happens on .NetCore on .NetFramework Task.Run async - await already works

After bringing this line to
```C#
Task.Run(() => { OpenSocketHandler(client); });

async Task OpenSocketHandler(...)
{
 await ExecuteOneHttpRequest();
} 
async Task ExecuteOneHttpRequest
{
  await smth else
}
```
I got 
```TXT
   System.ArgumentException: Task must be a Task<>
   at ArxOne.MrAdvice.Threading.TaskAccessor.Create(Task task)
   at ArxOne.MrAdvice.Invocation.GetResult(Task advisedTask, AdviceValues adviceValues)
   at ArxOne.MrAdvice.Threading.TaskContinuer`1.<>c__DisplayClass0_0`1.<ContinueWith>b__0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at ExecuteOneHttpRequest(HttpRequest httpRequest)
```

error happens on return from the method

**Comment by picrap** [comment]
Could you provide a small assembly that contains the code above? In MrAdvice code, the `GetResult` is invoked if the method is something else than `Task`, but I have no idea what it is. So a binary can help.

**Comment by hhblaze** [comment]
Let's start from 
```C#
 Task.Run(async () => { await OpenSocketHandler(client); });
```
problem, here is a [project TestMrAdvice02.zip](https://github.com/ArxOne/MrAdvice/files/2256485/TestMrAdvice02.zip)

The second mistake for me is hard to reproduce, it appears in a complex big project in case if I change correct  pattern 
```C#
 Task.Run(async () => { await OpenSocketHandler(client); });
```
on incorrect
```C#
 Task.Run(() => { OpenSocketHandler(client); });
```
(though it is probably wrong). 
May be after fixing the pattern such mistake will disappear - let's see. 
(And all the time we talk about .NetCore, in .NetFramework all works)

**Comment by hhblaze** [comment]
Ok, I could reproduce second bug also. Second bug happens with the AsyncAdvice.
Here is the [project TestMrAdvice02_2.zip](https://github.com/ArxOne/MrAdvice/files/2256842/TestMrAdvice02_2.zip)

**Comment by picrap** [comment]
Thanks. I'll use this to create a .NET core test assembly.

**Comment by hhblaze** [comment]
Works!
