### ISSUE TITLE
OutOfMemoryException when building Xamarin project

### ISSUE THREAD

**Issue by rgroenewoudt** [ArxOne/MrAdvice#138]
```
Internal error during Weavable methods detection: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at StitcherBoy.Weaving.Build.ReadonlyAssemblyResolver.LoadFile(String path)
   at StitcherBoy.Weaving.Build.ReadonlyAssemblyResolver.ResolveFromList(IAssembly assembly, IEnumerable`1 paths)
   at StitcherBoy.Weaving.Build.ReadonlyAssemblyResolver.ResolveFromReference(IAssembly assembly)
   at StitcherBoy.Weaving.Build.ReadonlyAssemblyResolver.Resolve(IAssembly assembly, ModuleDef sourceModule)
   at dnlib.DotNet.Resolver.Resolve(TypeRef typeRef, ModuleDef sourceModule)
   at ArxOne.MrAdvice.Weaver.TypeResolver.ResolverResolve(ITypeDefOrRef typeDefOrRef)
   at ArxOne.MrAdvice.Weaver.TypeResolver.DoResolve(ITypeDefOrRef typeDefOrRef)
   at ArxOne.MrAdvice.Weaver.TypeResolver.Resolve(ITypeDefOrRef typeRef)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.ResolveTypeOrGenericDefinition(ITypeDefOrRef typeDefOrRef)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.IsMarker(ITypeDefOrRef typeReference, ITypeDefOrRef markerInterface)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass46_0.<IsMarker>b__0(InterfaceImpl i)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.IsMarker(ITypeDefOrRef typeReference, ITypeDefOrRef markerInterface)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateAdviceSelector(ReflectionNode node, WeavingContext context)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.GetAdviceSelector(ReflectionNode node, WeavingContext context)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateAdviceSelector(ReflectionNode node, WeavingContext context)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.GetAdviceSelector(ReflectionNode node, WeavingContext context)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.IsIncludedByNode(MarkerDefinition markerDefinition, ReflectionNode node, WeavingContext context)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass37_1.<GetMarkedMethods>b__7(MarkerDefinition d)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass37_0.<GetMarkedMethods>b__3(<>f__AnonymousType2`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.Weave(ModuleDefMD moduleDefinition)		 	0	
```
When building Xamarin project.  It's not consistent, doesn't always happen.

**Comment by rgroenewoudt** [comment]
I'm seeing MSBuild.exe increasing to 1200MB when building but I'm not sure how much of that is MrAdvice.

**Comment by picrap** [comment]
Me neither... I'll take a look to make sure the same assembly is not loaded twice, but there's little chance I can fix this.

**Comment by rgroenewoudt** [comment]
I'm seeing a cache in ReadonlyAssemblyResolver that caches the entire assembly. Perhaps limit the cache to so many MB in case of large assemblies?

**Comment by rgroenewoudt** [comment]
Lately I haven't had any issues anymore.
