### ISSUE TITLE
System.IO.IOException

### ISSUE THREAD

**Issue by wilhelmmedetz** [ArxOne/MrAdvice#153]
I am sporadically getting the following errors

	Severity	Code	Description	Line	File	Project	Suppression State	Tool
	Error		Unhandled exception: System.IO.FileNotFoundException: Could not find file 'obj\Debug\net472\SimControl.Templates.CSharp.ConsoleApp.exe'.
	File name: 'obj\Debug\net472\SimControl.Templates.CSharp.ConsoleApp.exe'
	at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
	at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
	at StitcherBoy.Reflection.ModuleManager.LoadWithTemp(String assemblyPath, Nullable`1 useTemp)
	at StitcherBoy.Weaving.Build.AssemblyStitcher.LoadModule(String assemblyPath)
	at StitcherBoy.Weaving.Build.AssemblyStitcher.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAssemblyPath)
	at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
	at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
	at StitcherTask`1.Run(Boolean fromExe)	10	C:\Users\WilhelmMedetz\.nuget\packages\mradvice\2.8.8\build\MrAdvice.targets	SimControl.Templates.CSharp.ConsoleApp		MrAdviceTask

	Error		Unhandled exception: System.IO.IOException: Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar.
	at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
	at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
	at StitcherBoy.Reflection.ModuleManager.LoadWithTemp(String assemblyPath, Nullable`1 useTemp)
	at StitcherBoy.Weaving.Build.AssemblyStitcher.LoadModule(String assemblyPath)
	at StitcherBoy.Weaving.Build.AssemblyStitcher.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAssemblyPath)
	at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
	at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
	at StitcherTask`1.Run(Boolean fromExe)	10	C:\Users\WilhelmMedetz\.nuget\packages\mradvice\2.8.8\build\MrAdvice.targets	SimControl.Templates.CSharp.ConsoleApp		MrAdviceTask

The underlying system error seems to be ERROR_USER_MAPPED_FILE.
After starting another build the build usually succeeds (but the errors remain in the error window).

I will try to provide more detailed information.

**Comment by picrap** [comment]
Could you have an antivirus causing this?

**Comment by wilhelmmedetz** [comment]
I have only the default Windows 10 'Windows Defender' antivirus.

**Comment by picrap** [comment]
I don't have any other idea. It seems that another process tries to access the generated assembly, but it's hard to tell which one. Maybe you could try to disable defender or exclude the project directory from scan (this is recommended anyway)?

**Comment by wilhelmmedetz** [comment]
This problem only seems to occur when using multitarget projects

**Comment by picrap** [comment]
I now have the same with new SDK style-projects.

**Comment by wilhelmmedetz** [comment]
I ONLY use the new SDK style projects (mostly with multitarget configurations).

**Comment by wilhelmmedetz** [comment]
Any news for this issue?

**Comment by picrap** [comment]
Sorry, no, I did not work on it

**Comment by picrap** [comment]
Hi, there is a version 2.8.12 trying to fix this (this is a random problem, so it is hard to reproduce). I’m testing it right now in my other projects. Let me know if you have something better.

**Comment by wilhelmmedetz** [comment]
2.8.12 seems to fix this this issue
