### ISSUE TITLE
Error when executing 'Clean Solution' and 'Build Solution'

### ISSUE THREAD

**Issue by wilhelmmedetz** [ArxOne/MrAdvice#154]
When performing a `Clean Solution` and afterwards a `Build Solution` the following error occurs in the Errors window. The Build Output window states Build succeded with no errors. The error does not disappear after further successful builds.

	Error		Unhandled exception: System.IO.FileNotFoundException: Could not find file 'obj\Debug\net40\SimControl.Templates.CSharp.ConsoleApp.exe'.
	File name: 'obj\Debug\net40\SimControl.Templates.CSharp.ConsoleApp.exe'
	at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
	at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
	at StitcherBoy.Reflection.ModuleManager.LoadWithTemp(String assemblyPath, Nullable`1 useTemp)
	at StitcherBoy.Weaving.Build.AssemblyStitcher.LoadModule(String assemblyPath)
	at StitcherBoy.Weaving.Build.AssemblyStitcher.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAssemblyPath)
	at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
	at StitcherBoy.Weaving.StitcherProcessor.Process(StringDictionary parameters, Guid buildID, DateTime buildTime, String entryAsemblyPath)
	at StitcherTask`1.Run(Boolean fromExe)	10	C:\Users\WilhelmMedetz\.nuget\packages\mradvice\2.8.8\build\MrAdvice.targets	SimControl.Templates.CSharp.ConsoleApp		MrAdviceTask

**Comment by picrap** [comment]
I think this is the same problem as the other issue, so I sugguest you merge them. Since I still have no idea about the problem, I am going to feel a lighter burden with a fewer issues...

**Comment by wilhelmmedetz** [comment]
- I believe it are two separate problems.
- I can reproduce  this one every time with the above mentioned steps - `Clean Solution` and afterwards `Build Solution`.
- In this case, the files really _DO NOT EXIST_, as they have been deleted by `Clean Solution`.
- A repository to reproduce this can be found at https://github.com/SimControl/SimControl.Reactive
- I am using Visual Studio Enterprise 2019 16.3.7
- The Visual Studio `Build Output` does not contain the above error/Exception, even with `MSBuild project build output verbosity` set to `Diagnostic`, it only appears in the `Error List`.
- The error does not occur when executing `Rebuild Solution`.
- When monitoring both the `Error List` and the `Build Output` window, it seems as if the errors are displayed before building of the individual projects starts.

**Comment by wilhelmmedetz** [comment]
This problem only seems to occur when using multitarget projects

**Comment by wilhelmmedetz** [comment]
Thanks
2.8.12 seems to fix this this issue

**Comment by picrap** [comment]
This is a surprise (a good one), but OK
