### ISSUE TITLE
MrAdvice.Foody 1.1.9.0 Nuget, compilation error

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#51]
Project can't be compiled after referencing latest (1.1.9.0) Nuget MrAdvice.Foody (just added reference, nothing else was added)(Win 10 64bit .NET 4.5):

Severity	Code	Description	Project	File	Line
Error		Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
StackTrace:
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParameters()
   at System.RuntimeType.GetPropertyCandidates(String name, BindingFlags bindingAttr, Type[] types, Boolean allowPrefixLookup)
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at PropertyDelegateBuilder.BuildPropertySetDelegate[T](Type type, String propertyName) in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\DelegateBuilders\PropertyDelegateBuilder.cs:line 9
   at DelegateBuilder.BuildDelegateHolder(Type weaverType) in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\DelegateBuilders\DelegateBuilder.cs:line 25
   at DelegateBuilder.GetDelegateHolderFromCache(Type weaverType) in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\DelegateBuilders\DelegateBuilder.cs:line 16
   at InnerWeaver.InitialiseWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 111
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 61
Source:
mscorlib
TargetSite:
Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)	GM_YadroModule4

**Comment by picrap** [comment]
This is strange: the current version of Mr. Advice uses Fody 1.29.3 and Cecil 0.9.6.1 which are both the latest version of their product. So your error shows a request for Cecil 0.9.6.0, and this what I don't understand. Is there any way I can reproduce your problem?

**Comment by hhblaze** [comment]
[TestMrAdvice.zip](https://github.com/ArxOne/MrAdvice/files/58250/TestMrAdvice.zip)
So, I have created a blank DLL project and added Mr.Advice from Nuget. It can't be compiled. Complete project is embedded.

**Comment by picrap** [comment]
For some strange reason (I also had this problem once), your version of Fody (on which Mr. Advice relies) was outdated. Upgrading from 1.28 to 1.29 fixes the build.
I wanted to upload the fixed solution in a zip, but GitHub tells me it does not want it (WTF?).
Anyway, just upgrade Fody and you'll get a working solution. If it's OK, you can close this issue... And let me know what do you think of Mr. Advice :wink:

**Comment by hhblaze** [comment]
I have manually UPGRADED to Fody 1.29.3, and fixed FodyWeavers.xml to

<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <MrAdvice />
</Weavers>

..no works, thank you!

**Comment by hhblaze** [comment]
Mr.Advice will be under huge load test, PostSharp must go...

**Comment by picrap** [comment]
Mr. Advice is open source, so you're free (and welcome) to contribute.
Why leaving PostSharp? (I did the same, but I like to read other opinions).

**Comment by hhblaze** [comment]
PostSharp is not a part of open stack, that is bad for huge projects. 
We use only two aspects for all modules in our architecture. Performance counter and logged try..catch surrounding. For every method in DLLs is counted quantity of calls and execution time. We can monitor it real-time and make decision about the quality of the code. 
But PostSharp wants something more and always grows, makes some breaking changes. 
Actually now, we've a group of developers which still work with their modules on VS2012 and have to use PS v.3 (can't use v4) and others work with VS2015 where they MUST use PS v.4.

What is good in PS, in compare with all others AOP frameworks, is that they change IL code of the weaved method self, instead of making a wrapper:

```C#
return (string)Invocation.ProceedAdvice(this, null, MethodBase.GetCurrentMethod(), MethodBase.GetMethodFromHandle(methodof(Class1.Test​()).MethodHandle), false, null);
```

PS must be a bit faster.
