### ISSUE TITLE
Fody: An unhandled exception occurred after upgrading MrAdvice

### ISSUE THREAD

**Issue by raflop** [ArxOne/MrAdvice#53]
Hi,

After upgrading MrAdvice from MrAdvice.Fody.1.1.9 to MrAdvice.Fody.1.2.3 i'm getting following error during build:

Severity Code Description Project File Line Suppression State
Error  Fody: An unhandled exception occurred:
Exception:
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ModuleWeaver.Execute()
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
mscorlib
TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
Could not load file or assembly 'MrAdvice, Version=1.2.3.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8' or one of its dependencies. An error relating to remoting occurred. (Exception from HRESULT: 0x8013150B)
StackTrace:
   at ArxOne.MrAdvice.Weaver.AspectWeaver.Weave(ModuleDefinition moduleDefinition)
   at ModuleWeaver.Execute()
Source:
MrAdvice.Weaver
TargetSite:
Void Weave(Mono.Cecil.ModuleDefinition)
Object '/d7c98439_1587_4fcf_8984_6e3dbb9f50b3/wqxikqsmin706d4l+zcg+rd3_403.rem' has been disconnected or does not exist at the server.
StackTrace:

Server stack trace: 
   at System.Runtime.Remoting.Channels.ChannelServices.CheckDisconnectedOrCreateWellKnownObject(IMessage msg)
   at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at ILogger.LogInfo(String message)
   at InnerWeaver.<SetProperties>b__88_1(String s) in C:\projects\fody\FodyIsolated\WeaverInitialiser.cs:line 25
   at ModuleWeaver.OnAssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
Source:
mscorlib
TargetSite:
System.Runtime.Remoting.ServerIdentity CheckDisconnectedOrCreateWellKnownObject(System.Runtime.Remoting.Messaging.IMessage) 

Best regards

**Comment by picrap** [comment]
Hi, sorry to read that. Is this always the case or does it occur randomly?

**Comment by picrap** [comment]
Have you tried removing the package and reinstalling it? It may come from two coexisting packages with different versions.

**Comment by raflop** [comment]
This is happening always, in my current project. I will try to repeat this problem in some new test project, but actually i don't have any idea on what code MrAdvice is failing.

I can say only that the similar problem was with version 1.2.0 then it was fixed in version 1.2.1 (but async code stoped working)

**Comment by raflop** [comment]
Version 1.2.4 works, thanks a lot :)

**Comment by picrap** [comment]
:laughing: 
I actually did nothing to solve this... Just added a .ToArray() in some enumeration between 1.2.3 and 1.2.4.
And it may just have solved the problem...
Amazing!
So I close the issue.
