### ISSUE TITLE
methodAdviceContext.Proceed() throws an invocation exception on a Generic method that has a where constraint

### ISSUE THREAD

**Issue by shirbr510** [ArxOne/MrAdvice#64]
Hi Pascal.

I have a class with many Gets that applies to the given interface:

```
public interface IProviderFactory
    {
        IAvailableProjectWrapperProvider GetAvailableProjectProvider();
        IPromoterProvider GetPromoterProvider();
        IContactProvider<T> GetContactProvider<T>() where T : Contact;
        IConnectedContactProvider GetConnectedContactProvider();
        IDocumentProvider GetDocumentsProvider();
        IPictureProvider GetPicturesProvider();
        IVideoProvider GetVideosProvider();
        IProjectAsyncProvider<T> GetGeneralProjectProvider<T>() where T : GeneralProject;
        IStructureProvider GetStructureProvider();
        IUserProvider GetUserProvider();
        IPaymentWrapperProvider<T> GetPaymentProvider<T>() where T : PaymentWrapper;
        IResellerProvider GetResellerProvider();
        IUsersConnectionDetailsProvider GetIUsersConnectionDetailsProvider();
        IGeneralVoteProvider GetGeneralVoteProvider();
        ISmartAgentPropertyProvider GetSmartAgentPropertyProvider();
        IGeneralClassCodeProvider GetGeneralClassCodeProvider();
        IClassCodeUpdater GetGeneralClassCodeUpdater();
        IUnderConstructionGeneralProjectProvider GetUnderConstructionProjectProvider();
        IGeneralProjectTreeAsyncProvider GetGeneralProjectTreeProvider();
        ISessionsProvider GetSessionsProvider();
    }
```

I have decorated it with an AdviceAttribute and everything goes normal until getting to method `GetGeneralProjectProvider<T>()`.

the attribute works fine until the `methodAdviceContext.Proceed()` throws a `TargetInvocationException` on the call to the method.

the error's message is:

`GenericArguments[0], 'T', on 'BuildinClickDAL.Providers.Projects.Abstract.IProjectProvider`1[T]' violates the constraint of type parameter 'T'.`

the error's stack trace is : 

```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ArxOne.MrAdvice.Advice.InnerMethodContext.Invoke()
   at ArxOne.MrAdvice.Advice.SyncAdviceContext.Proceed()
   at Buildin.Infrastructure.Logging.Attributes.LogThisAttribute.Advise(MethodAdviceContext context) in C:\Git\BuildinClick\BuildinClickAPI\Buildin.Infrastructure\Logging\Attributes\LogThisAttribute.cs:line 32
   at ArxOne.MrAdvice.Advice.MethodAdviceContext.Invoke()
   at ArxOne.MrAdvice.Invocation.ProceedAdvice(Object target, Object[] parameters, MethodBase methodBase, MethodBase innerMethod, Boolean abstractedTarget, Type[] genericArguments)
   at BuildinClickMongoDAL.Factories.MongoProviderFactory.GetGeneralProjectProvider[T]()
   at BuildinClickWebApi.Jobs.SmartAgentJob..ctor() in C:\Git\BuildinClick\BuildinClickAPI\BuildinClickWebApi\Jobs\SmartAgentJob.cs:line 30
```

also, there is an inner excpetion with stack trace:

```
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()
   at System.Exception.PrepForRemoting()
```

what am I missing?

I think it might be a bug

**Comment by picrap** [comment]
This looks like a bug... I am going to investigate on it.

**Comment by shirbr510** [comment]
Thank you. also it also just re-occurred on another method with
generic constraint so I guess it is rather easy to reproduce

**Comment by shirbr510** [comment]
Hi Pascal.
have you checked on this issue?
I'm looking forward for your answer/ solution.

if you need any more data or help, please have me notified :)

**Comment by picrap** [comment]
Keep calm and enjoy July :) It's summer, time for holidays.

Anyway, I was trying to reproduce the problem, without success. Are you telling me that you advise an interface directly? Or do you apply the advice to the implementation class?

**Comment by shirbr510** [comment]
oh, sorry mate :)

I'll give you one example that it occurs at:

I'm placing the Advice over the implementing class of this interface:

```
public interface IProviderFactory
    {
        IAvailableProjectWrapperProvider GetAvailableProjectProvider();
        IPromoterProvider GetPromoterProvider();
        IContactProvider<T> GetContactProvider<T>() where T : Contact;
        IConnectedContactProvider GetConnectedContactProvider();
        IDocumentProvider GetDocumentsProvider();
        IPictureProvider GetPicturesProvider();
        IVideoProvider GetVideosProvider();
        IProjectAsyncProvider<T> GetGeneralProjectProvider<T>() where T : GeneralProject;
        IStructureProvider GetStructureProvider();
        IUserProvider GetUserProvider();
        IPaymentWrapperProvider<T> GetPaymentProvider<T>() where T : PaymentWrapper;
        IResellerProvider GetResellerProvider();
        IUsersConnectionDetailsAsyncProvider GetIUsersConnectionDetailsProvider();
        IGeneralVoteProvider GetGeneralVoteProvider();
        ISmartAgentPropertyProvider GetSmartAgentPropertyProvider();
        IGeneralClassCodeProvider GetGeneralClassCodeProvider();
        IClassCodeUpdater GetGeneralClassCodeUpdater();
        IUnderConstructionGeneralProjectProvider GetUnderConstructionProjectProvider();
        IGeneralProjectTreeAsyncProvider GetGeneralProjectTreeProvider();
        ISessionsProvider GetSessionsProvider();
    }
```

the exception is being thrown while calling the`GetGeneralProjectProvider` method.

I'll also state that the return type of this method is following this interface defenition

```
public interface IProjectAsyncProvider<T> : IProjectProvider<T>, IGenericAsyncProvider<T> where T : IProject
    {
        Task<IEnumerable<T>> GetAllProjectsForSaleByPromoterIdAsync(string promoterId);
        Task<IEnumerable<T>> GetAllProjectsForSaleByResellerIdAsync(string resellerId);
        Task<IEnumerable<T>> GetAllProjectsConnectedToUserIdAsync(string userId);
        Task<IEnumerable<IGeneralUser>> GetUsersAsync(string projectId);
        Task<IEnumerable<T>> GetProjectsByAreaAsync(IArea area);
        Task<IEnumerable<T>> GetAllProjectsByPromoterIdAsync(string promoterId);
        Task<IEnumerable<T>> GetAllProjectsByResellerIdAsync(string resellerId);
        Task<IEnumerable<string>> GetAllGeneralProjectsIdsAsync();
        Task<IEnumerable<string>> GetAllProjectsIdsByPromoterIdAsync(string promoterId);
        Task<IEnumerable<ProjectAdvertisingContext>> GetAdvertisingContextsAsync();
    }
```

as you can see, `IProjectAsyncProvider` requires the `T` to be a `IProject` and the `GetGeneralProjectProvider` requires the `T` to be a `GeneralProject`.

but that's ok cause `GeneralProject` implements `IProject`


if you need any more information, do tell :)

**Comment by picrap** [comment]
Let me know if this works with 1.3.1

**Comment by picrap** [comment]
Let me know if this works with 1.3.1

**Comment by shirbr510** [comment]
seems like everything is in working order!

thank you so much for your time and support :)
